config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :buyers, controllers: { registrations: 'buyers/registrations' }
  # devise_for :buyers, controllers: { registration: 'buyers/registrations' }
  resources :orders
  resources :carts
  # devise_for :buyers
  resources :stores
  devise_for :sellers
  devise_for :admins
  get 'products/myproducts'
  resources :product_attachments
  resources :products
  resources :brands
  resources :cart_carry, :controller => "cart_carries"
  resources :categories
  get 'order/seller', to: 'orders#seller' ,as:'sallerView'
  post 'order/seller/accept/:id', to: 'orders#accept' ,as:'sallerAccept'
  post 'order/seller/reject/:id', to: 'orders#reject' ,as:'sallerReject'






  match 'cart/checkout' => 'carts#checkout',:via => [:post], :as => 'cart_checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :Product
    validates :name, presence: true, uniqueness: true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart
  has_many :order
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :buyer

    has_many :CartCarry
    has_many :Product, through: :CartCarry
end

app/models/cart_carry.rb
class CartCarry < ApplicationRecord
    belongs_to :cart 
    belongs_to :product 
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :Product
    validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :buyer , optional: true

    has_many :OrderItems
    has_many :Products, through: :OrderItems
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order 
    belongs_to :product 
    belongs_to :seller 

end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :quantity, presence: true
    validates :currentPrice, presence: true
    validates :description, presence: true

    paginates_per 3

    has_many :ProductAttachment, dependent: :destroy
    accepts_nested_attributes_for :ProductAttachment #, reject_if: proc { |attributes| attributes['photos'].blank? }

    
    belongs_to :store 

    has_many :CartCarry
    has_many :Cart, through: :CartCarry

    belongs_to :brand 
    belongs_to :category 

    
    has_many :OrderItems
    has_many :Order, through: :OrderItems




    def self.search(search)
        if search
            Product.where("name LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
        else
          Product.all
        end
    end


    
    def self.cat(search)
        if search
            Product.where("category_id = ?", "#{search}")
        else
          Product.all
        end
    end



    def self.brand(search)
        if search
            Product.where("brand_id = ? ", "#{search}")
        else
          Product.all
        end
    end


    def self.seller(search)
        if search
            Product.where("store_id = ?", "#{search}")
        else
          Product.all
        end
    end




    def self.price(min,max)
        
            Product.where(currentPrice: min..max)
        
    end


end

app/models/product_attachment.rb
class ProductAttachment < ApplicationRecord
    belongs_to :product
    validates :photo, :product_id, presence: true
    mount_uploader :photo, PhotosUploader
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to  :store , optional: true
  has_many :OrderItems
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :Product
    has_one :Seller 
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  before_action :authenticate_admin!
  def create
    @store = Store.new(store_params)
    @seller = Seller.find_by(id: seller_store_param[:seller_id])
    # @store.Seller.where(id: seller_store_param[:seller_id]).update_all(:store_id => @store)
    
    Rails.logger.info(@store.inspect)
    
    # puts "HEEEREEE"
    # puts seller_store_param
    respond_to do |format|
      if @store.save
        @seller.store_id = @store.id
        @seller.save
         
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :summary)
    end

    def seller_store_param
      params.require(:store).permit(:seller_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_carries_helper.rb
module CartCarriesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: 'form-control'  %>
  </div>

<br />
<div class="field">
<%= form.label :Store_Admin %>
<%= form.collection_select :seller_id, Seller.where(store_id: nil), :id, :email, include_blank: true, class: 'form-select'  %>
</div>
  <div class="actions">
    <%= form.submit :button_to , value: 'New', class: 'btn btn-outline-primary float-end'%>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store  , class: 'btn btn-outline-primary'%> 
<%= link_to 'Back', stores_path  , class: 'btn btn-outline-primary'%>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Store', new_store_path ,class: 'btn btn-outline-success float-end m-1' %>
<h1>Stores</h1>

<table class="table table-dark table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.summary %></td>
        <td><%= link_to 'Show', store , class: 'btn btn-outline-info' %></td>
        <td ><%= link_to 'Edit', edit_store_path(store),class: 'btn btn-outline-warning' %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path , class: 'btn btn-outline-primary'%>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @store.summary %>
</p>

<%= link_to 'Edit', edit_store_path(@store) , class: 'btn btn-outline-primary' %> 
<%= link_to 'Back', stores_path , class: 'btn btn-outline-primary' %>