config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :buyers, controllers: { registrations: 'buyers/registrations' }
  # devise_for :buyers, controllers: { registration: 'buyers/registrations' }
  resources :orders
  resources :carts
  # devise_for :buyers
  resources :stores
  devise_for :sellers
  devise_for :admins
  get 'products/myproducts'
  resources :product_attachments
  resources :products
  resources :brands
  resources :cart_carry, :controller => "cart_carries"
  resources :categories
  get 'order/seller', to: 'orders#seller' ,as:'sallerView'
  post 'order/seller/accept/:id', to: 'orders#accept' ,as:'sallerAccept'
  post 'order/seller/reject/:id', to: 'orders#reject' ,as:'sallerReject'






  match 'cart/checkout' => 'carts#checkout',:via => [:post], :as => 'cart_checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :buyer

    has_many :CartCarry
    has_many :Product, through: :CartCarry
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_buyer!
  before_action :set_cart, only: %i[show edit update destroy]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    @cart = Cart.find_by(buyer_id:current_buyer.id)
    @entries = CartCarry.where(cart_id:@cart.id)
    @TotalPrice = 0
    @entries.each do |item|
     @TotalPrice += Product.find_by(id:item.product_id).currentPrice * item.quantity
    end
  end

  # GET /carts/new
  def new  
    @cart = Cart.find_by(buyer_id:current_buyer.id)
    @p = Product.find_by(id:params[:product])
    session[:passed_variable] = @p.id

    if params[:quantity] != nil
      session[:edited_Quantity] = params[:quantity]
      puts "YO"
    else
      puts "NOO"
    end
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    # @cart = Cart.new(cart_params)

    # respond_to do |format|
    #   if @cart.save
    #     format.html { redirect_to @cart, notice: "Cart was successfully created." }
    #     format.json { render :show, status: :created, location: @cart }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @cart.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    @first_value = session[:passed_variable] 
    @get_value = @first_value
    @p = Product.find_by(id:@get_value)



    puts @p.name 
    puts cart_params["quantity"]

    
    if cart_params["quantity"].to_i > @p.quantity
      puts "LAAAAAAAAAAAAAA"
       flash.now[:danger] = "You cannot order more than the product's quantity"
       render :new

    else
        @cart = Cart.find_by(buyer_id:current_buyer.id)
        @editing_Quantity = session[:edited_Quantity]
        puts "FOUND CART"

        if @editing_Quantity != nil
          @entry = CartCarry.find_by(cart_id:@cart.id , product_id:@p.id)
          puts "Cart Carry"
          puts "EDITING"
          @entry.quantity = cart_params["quantity"]
          @entry.save
          session[:edited_Quantity] = nil
        else
          puts "ADDING"
          @entry = CartCarry.create(cart_id:@cart.id,product_id:@p.id,quantity: cart_params["quantity"].to_i)
          Rails.logger.info(@entry.errors.inspect)     
        end
         respond_to do |format|
           format.html { redirect_to cart_path, notice: "Product added to cart" }
         end
    end



    # respond_to do |format|
    #   if @cart.update(cart_params)
    #     format.html { redirect_to @cart, notice: "Cart was successfully updated." }
    #     format.json { render :show, status: :ok, location: @cart }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @cart.errors, status: :unprocessable_entity }
    #   end
    # end
  end


  def checkout
    puts "CHECKED OUT"
    @cart = Cart.find_by(buyer_id:current_buyer.id)
    @items = CartCarry.where(cart_id:@cart.id)
    if @items != nil
      @order = Order.create(state: "Pending", buyer_id:current_buyer.id)
      @items.each do |item|
        @product_for_this_item = Product.find_by(id: item.product_id)
        if @product_for_this_item.quantity >= item.quantity
          @store = Store.find_by(id: @product_for_this_item.store_id)
          @seller = Seller.find_by(store_id: @store.id)
          @order_items = OrderItem.create(state: "Pending", priceAtBuyTime:@product_for_this_item.currentPrice ,
           order_id: @order.id, product_id: item.product_id, seller_id:@seller.id,quantity:item.quantity)
          item.destroy
        else
          redirect_to root_path
          return
        end
      end

     # @order = Order.create(state: "Pending", buyer_id:current_buyer.id)
      
      # @items.each do |item|
      #   puts item.seller_id
      
      # end
    end
    respond_to do |format|
        format.html { redirect_to cart_path(:id => Cart.find_by(buyer_id:current_buyer.id).id), notice: "Checked Out" }
    end

  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find_by(buyer_id:current_buyer.id)
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:quantity)
    end
    # def addToCart
    #     params.permit(:quantity)
    # end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity , class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit :button_to , value: 'New', class: 'btn btn-outline-primary float-end' %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart , class: 'btn btn-outline-primary' %> |
<%= link_to 'Back', carts_path , class: 'btn btn-outline-primary' %>
 

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table class="table table-dark table-hover">
  <thead>
    <tr>
      <th>Buyer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.buyer_id %></td>
        <td><%= link_to 'Show', cart , class: 'btn btn-outline-info' %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart),class: 'btn btn-outline-warning'  %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-outline-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>ADD TO CART</h1>


<% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
<% end %>



<p>
  <strong>Name:</strong>
  <%= @p.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @p.quantity %>
</p>

<p>
  <strong>Currentprice:</strong>
  <%= @p.currentPrice %>
</p>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path , class: 'btn btn-outline-primary'%>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>


 <% if @entries.count != 0 %>
 <h1 class="fs-3 fw-bold ">Total Price:   <%=@TotalPrice%></h1>
<table class="table text-white">
  <thead><th>Product Name</th><th>Quantity</th><th>Price</th><th>Change Quantity</th><th>Remove From cart</th></thead>
  <tbody>

     <% @entries.each do |item|%>
      <tr>
        <td> <%=link_to Product.find_by(id:item.product_id).name, product_path(:id => item.product_id) ,class: 'fs-3 fw-bold' %>  </td>
        <td class="fs-3 fw-bold "> <%= item.quantity%> </td>
        <td class="fs-3 fw-bold "> <%= Product.find_by(id:item.product_id).currentPrice * item.quantity%> </td>
        <td> <%= link_to 'Edit Quantity', new_cart_path(:product => item.product_id, :quantity=>item.quantity), class: 'btn btn-outline-success' %> </td>
        <td><%= link_to 'Remove Item', item ,method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-outline-danger' %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
    <%= link_to 'Checkout',cart_checkout_path , method: :post , class: 'btn btn-outline-primary m-4'%>

<% else %>
<h1>WOW such empty</h1>

 <% end %>

<%= link_to 'Back', root_path , class: 'btn btn-outline-primary' %>