config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :buyers, controllers: { registrations: 'buyers/registrations' }
  # devise_for :buyers, controllers: { registration: 'buyers/registrations' }
  resources :orders
  resources :carts
  # devise_for :buyers
  resources :stores
  devise_for :sellers
  devise_for :admins
  get 'products/myproducts'
  resources :product_attachments
  resources :products
  resources :brands
  resources :cart_carry, :controller => "cart_carries"
  resources :categories
  get 'order/seller', to: 'orders#seller' ,as:'sallerView'
  post 'order/seller/accept/:id', to: 'orders#accept' ,as:'sallerAccept'
  post 'order/seller/reject/:id', to: 'orders#reject' ,as:'sallerReject'






  match 'cart/checkout' => 'carts#checkout',:via => [:post], :as => 'cart_checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :quantity, presence: true
    validates :currentPrice, presence: true
    validates :description, presence: true

    paginates_per 3

    has_many :ProductAttachment, dependent: :destroy
    accepts_nested_attributes_for :ProductAttachment #, reject_if: proc { |attributes| attributes['photos'].blank? }

    
    belongs_to :store 

    has_many :CartCarry
    has_many :Cart, through: :CartCarry

    belongs_to :brand 
    belongs_to :category 

    
    has_many :OrderItems
    has_many :Order, through: :OrderItems




    def self.search(search)
        if search
            Product.where("name LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
        else
          Product.all
        end
    end


    
    def self.cat(search)
        if search
            Product.where("category_id = ?", "#{search}")
        else
          Product.all
        end
    end



    def self.brand(search)
        if search
            Product.where("brand_id = ? ", "#{search}")
        else
          Product.all
        end
    end


    def self.seller(search)
        if search
            Product.where("store_id = ?", "#{search}")
        else
          Product.all
        end
    end




    def self.price(min,max)
        
            Product.where(currentPrice: min..max)
        
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_seller!, except: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index

    if params[:category]
      @products = Product.cat(params[:category]).order(:created_at).page(params[:page])
    elsif params[:brand]
      @products = Product.brand(params[:brand]).order(:created_at).page(params[:page])
    elsif params[:store]
      @products = Product.seller(params[:store]).order(:created_at).page(params[:page])
    elsif params[:minprice] || params[:maxprice]
      @products = Product.price(params[:minprice], params[:maxprice]).order(:currentPrice).page(params[:page])
      #@products = Product.where(currentPrice:  0..2000)
      puts 'hy'
      #Product.price(params[:price])
    else
      @products = Product.search(params[:search]).order(:created_at).page(params[:page])
    end

    # @products = Product.where("category_id = 3")

    # puts params[:name]

    #@products = Product.all

    # @admin = current_seller
  end

  # GET /products/1 or /products/1.json
  def show
    @product_attachments = @product.ProductAttachment.all
  end

  # GET /products/new
  # before_action :authenticate_seller!, :check_for_store_id , only: :new
  def new
    @product = Product.new
    @product_attachments = @product.ProductAttachment.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json

  def create
    puts "YOOO"
    @product = Product.new(product_params)
    @product.store_id = current_seller.store_id
    respond_to do |format|
      if params[:product_attachments]
        if @product.save
          unless defined? params[:product_attachments]['photos']
            @product_attachments = @product.ProductAttachment.create!(:photo => "", :product_id => @product.id)
          else
            params[:product_attachments]['photos'].each do |a|
              @product_attachments = @product.ProductAttachment.create!(:photo => a, :product_id => @product.id)
            end
          end
          format.html { redirect_to @product, notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to new_product_path, notice: "Photo is not found" }
        format.json { render json: @product.errors, status: :unprocessable_entity}
      end
    end

  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def myproducts
    @myProducts = Product.where("store_id=#{current_seller.store_id}")
  end

  private

  def check_for_store_id
    puts "HEL:LLLLLOOO"
    puts current_seller.store_id.nil?
    if @current_seller.store_id.nil?
      redirect_to products_url, notice: "You Dont own a store"
      return
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :quantity, :currentPrice, :brand_id, :category_id, :description, product_attachments_attributes:
      %i[id product_id photos])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  

  <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :currentPrice %>
    <%= form.number_field :currentPrice, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
<br />
<div class="field">
<%= form.label :Brand %>
  <%= form.collection_select :brand_id, Brand.all, :id, :name, include_blank: true, class: 'form-select' %>
  </div>
<br />
  <div class="field">
  <%= form.label :Category %>
  <%= form.collection_select :category_id, Category.all, :id, :name, include_blank: true, class: 'form-select'  %>
  </div>


    <%= form.fields_for :product_attachments do |p| %>
         <div class="field">
           <%= p.label :photos %><br>
           <%= p.file_field :photos, :multiple => true, name:     "product_attachments[photos][]" %>
         </div>
       <% end %>
<br />
  <div class="actions">
    <%= form.submit :button_to , value: 'New', class: 'btn btn-outline-primary float-end' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product , class: 'btn btn-outline-primary' %> 
<%= link_to 'Back', products_path , class: 'btn btn-outline-primary' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


<% if seller_signed_in?%>

<%= link_to 'New Product', new_product_path , class: 'btn btn-outline-primary float-start'%>
<br/>
<% end %>
<br/>
<h1>Products</h1>




 
        
          <%= form_tag(products_path, method: :get) do %>
            

            <div class="input-group mb-3 w-75">
              <%= submit_tag("Search products", :name => nil, style: "color: black;", class:"btn btn-primary",style: "color: white;") %>
              <%= text_field_tag(:search, params[:search],class:"form-control ",style: "background-color: white;width: 50px;") %>
            </div>
              

              
          <% end %>

          <br>


    <h2> Filter by </h2>
<div class="container">
  <div class="row row-cols-auto ">

<div class="col">
    <div class ="btn-group">

              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <% Category.all.each do |category| %>
                    <li><%= link_to category.name, root_path(category: category.id), class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </div>

    </div>
  </div>

<div class="col">
    <div class ="btn-group">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Brand
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <% Brand.all.each do |brand| %>
                    <li><%= link_to brand.name, root_path(brand: brand.id), class: "dropdown-item" %></li>
                  <% end %>
                </ul>
            </div>

    </div>
</div>


<div class="col d-inline">
    <div class ="btn-group">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Seller
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <% Store.all.each do |store| %>
                    <li><%= link_to store.name, root_path(store: store.id), class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </div>


    </div>
</div>

  <div class="col col-lg-4">
  </div>
  
  
<div class="col">
   
     <%= form_tag(products_path, method: :get) do %> 
     
              
              <%= submit_tag("Price Range", :name => nil, style: "color: white;",class: "btn btn-secondary") %>   
              <%= text_field_tag(:minprice, params[:minprice],class:"form-control d-inline-block",style: "background-color: white;width: 100px; color:black;") %> :
              <%= text_field_tag(:maxprice, params[:maxprice],class:"form-control d-inline-block",style: "background-color: white;width: 100px; color:black;") %> 

      <% end %>

</div>


</div>
  </div>
    
<br>

    
    <br>
    <br>







<div class="row row-cols-1 row-cols-md-3">
    <% @products.each do |product| %>
        <div class="col mb-4">
          <div class="card bg-dark h-100" style="width: 18rem;">
               <%= image_tag "#{product.ProductAttachment.first.photo}",class:"card-img-top h-50" %>
              <div class="card-body">
                <h5 class="card-title mb-3"><%= product.name %></h5>
                <h6 class="card-subtitle mb-2 "> <span style="color: #004d99;font-size: 20px;font-weight: bold;">Category:</span> <%= Category.find(product.category_id).name %></h6>
                <h6 class="card-subtitle mb-2 "> <span style="color: #004d99;font-size: 20px;font-weight: bold;">Brand:</span> <%= Brand.find(product.brand_id).name %></h6>
                <h6 class="card-subtitle mb-2 "> <span style="color: #004d99;font-weight: bold;">quantity:</span> <%= product.quantity %></h6>
                <h6 class="card-subtitle mb-2"><span style="color: #004d99;font-weight: bold;">price:</span> <%= product.currentPrice %></h6>
                <span style="color: #004d99;font-size: 25px;">Description:</span>
                <p class="card-text" style="font-size: 20px;"> <%= product.description %></p>
                <button class="btn btn-secondary"><%= link_to 'Show item', product, style: "color: white; text-decoration: none;"  %></button>
              </div>
            </div>
          </div>
      <% end %>

</div>


<%=  paginate @products%>

<br>

app/views/products/myproducts.html.erb
<div class="mt-4">
<%= link_to 'New Product', new_product_path, class: 'btn btn-primary float-end' %>
<h1 class="mb-4 mt-4">My Products :</h1>

<p id="notice"><%= notice %></p>
<% if @myProducts.size == 0 %>
  <h2>YOU DON'T HAVE ANY PRODUCTS YET</h2>
<% else %>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col" class="p-3">ID</th>
      <th scope="col" class="p-3">Name</th>
      <th scope="col" class="p-3">Quantity</th>
      <th scope="col" class="p-3">Currentprice</th>
      <th scope="col" class="p-3">Description</th>
      <th scope="col" class="p-3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myProducts.each do |product| %>
      <tr>
        <th scope="row" class="p-3"><%= product.id %></th>
        <td class="p-3"><%= product.name %></td>
        <td class="p-3"><%= product.quantity %></td>
        <td class="p-3"><%= product.currentPrice %></td>
        <td class="p-3"><%= product.description %></td>
        <td class="p-3"><%= link_to 'Show', product, class: 'btn btn-info' %>
        <%= link_to 'Edit', edit_product_path(product) , class: 'btn btn-primary' %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<br>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<p id="notice" style="color: #B00100"><%= notice %></p>

<%= render 'form', product: @product , class: 'btn btn-outline-primary'%>

<%= link_to 'Back', products_path , class: 'btn btn-outline-primary' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card mb-5 bg-dark" style="max-width: 100%">
  <div>
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <% @product.ProductAttachment.drop(1).each_with_index do |item, index| %>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%=  index+1  %>" aria-label="Slide 2"></button>
        <% end %>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag("#{@product.ProductAttachment.first.photo}", width: '100%', height:'500',class:"rounded d-block w-100")%>
        </div>
        <% @product.ProductAttachment.drop(1).each do |image| %>
          <div class="carousel-item">
            <%= image_tag("#{image.photo}", width: '100%', height:'500',class:"rounded d-block w-100")%>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <br>
    <div class="col-sm-7">
      <div class="card-body">
        <h1 class="card-title" style="font-family: 'serif'"><%= @product.name %></h1>
        <hr>
        <p class="card-text">
          <p>
            <strong>Quantity :</strong>
            <%= @product.quantity %>
          </p>
          <p>
            <strong>Currentprice :</strong>
            <%= @product.currentPrice %>
          </p>
          <p>
            <strong>Description :</strong>
            <%= @product.description %>
          </p>
          <p>
            <strong>Brand :</strong>
            <%= Brand.find_by(id:@product.brand_id ).name%>
          </p>
          <p>
            <strong>Category :</strong>
            <%= Category.find_by(id:@product.category_id).name %>
          </p>
          <%= link_to 'Add To Cart', new_cart_path(:product => @product.id), class: 'btn btn-success' %>
          <%= link_to 'Back', products_path, class: 'btn btn-light' %>
        </p>
      </div>
    </div>
  </div>
</div>